# Generated by Django 2.1.3 on 2020-06-13 15:32

from django.db import migrations, models
import ventas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to=ventas.models.Producto.url),
        ),
    ]
