# Generated by Django 2.1.3 on 2020-06-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caregoria',
            field=models.ManyToManyField(blank=True, null=True, to='ventas.Category'),
        ),
    ]
